version: '3.7'

services:
  server:
    depends_on: [redis]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8787:8787
    environment:
      - KV_PERSIST=redis://redis:6379
    
  redis:
    ports:
    - 6379:6379
    image: redis
    