name: 'Workflow Dispatch'
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    name: 'Lint'
    uses: ./.github/workflows/lint.yml

  call-build:
    name: 'Build'
    needs: call-lint
    uses: ./.github/workflows/build.yml

  call-test:
    name: 'Test'
    needs: call-lint
    uses: ./.github/workflows/test.yml

  call-deploy:
    name: 'Deploy'
    uses: './.github/workflows/deploy.yml'
    secrets: inherit
